# ASP.NET Core (.NET Framework)

trigger:
 branches:
  include:
    - master
 paths:
  include:
    - 'LorryLogAdmin/*'
   

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  project: '**/LorryLogAdmin/LorryLogAdmin.csproj'
  outputdir: '**/LorryLogAdmin'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Development'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(project)'
    workingDirectory: '$(outputdir)'


